### ISSUE TITLE
TypeError: Cannot read property 'stemmer' of undefined

### ISSUE THREAD

**Issue by ashish-k-mi** [pavelvlasov/mongoose-search-plugin#9]
var stemmer = natural[options.stemmer || 'PorterStemmer'],
                                     ^

TypeError: Cannot read property 'stemmer' of undefined
    at module.exports (/home/Downloads/Web-Dev/Projects/sam-app/node_modules/mongoose-search-plugin/index.js:8:3
1)
    at Object.<anonymous> (/home/Downloads/Web-Dev/Projects/sam-app/models/reports.js:36:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/Downloads/Web-Dev/Projects/sam-app/routes/index.js:21:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/Downloads/Web-Dev/Projects/sam-app/app.js:15:21)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
Program node bin/www exited with code 1

**Comment by BobCaSUaL** [comment]
Use `report.plugin(searchplugin, options)` as you done with autoincrementPlugin.
